---
- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - role: prereq

- hosts: balancer
  become: yes
  roles:
    - role: balancer

- hosts: k8s_cluster
  become: yes
  roles:
    - role: docker

- hosts: controller
  become: yes
  roles:
    - role: k8s/controller

- hosts: controller
  become: yes
  roles:
    - role: k8s/cni

- hosts: controller
  become: yes
  roles:
    - role: metallb

- hosts: worker
  become: yes
  roles:
    - role: k8s/worker