---
- hosts: all
  gather_facts: true
  become: true
  roles:
    - role: prereq

- hosts: balancer
  become: true
  roles:
    - role: balancer

- hosts: k8s_cluster
  become: true
  roles:
    - role: docker

- hosts: controller
  become: true
  roles:
    - role: k8s/controller
      vars:
        k8s_version_split: "{{k8s_version.split('.')}}" 

- hosts: controller
  become: true
  roles:
    - role: k8s/cni

- hosts: worker
  become: true
  roles:
    - role: k8s/worker
      vars:
        k8s_version_split: "{{k8s_version.split('.')}}" 
