- name: Install MetalLB
  block: 

  - name: Download metallb namespace manifest to first controller
    ansible.builtin.get_url:
      url: "https://raw.githubusercontent.com/metallb/metallb/{{metallb_version}}/manifests/namespace.yaml"
      dest: ~/metallb-namespace.yml
      mode: 0664
  
  - name: Download metallb main manifest to first controller
    ansible.builtin.get_url:
      url: "https://raw.githubusercontent.com/metallb/metallb/{{metallb_version}}/manifests/metallb.yaml"
      dest: ~/metallb.yml
      mode: 0664
  
  - name: Create metallb namespace
    k8s:
      kubeconfig: "/home/{{ ansible_user }}/.kube/config" 
      state: present              
      src: ~/metallb-namespace.yml
    when: 
      - ansible_host == hostvars[groups['controller'][0]]['ansible_host'] | default(groups['controller'][0])
  
  - name: Install metallb
    k8s:
      kubeconfig: "/home/{{ ansible_user }}/.kube/config" 
      state: present              
      src: ~/metallb.yml
    when: 
      - ansible_host == hostvars[groups['controller'][0]]['ansible_host'] | default(groups['controller'][0])
  
  - name: Copy metallb ConfigMap manifest to first controller
    template:
      src: "metallb.configmap.j2"
      dest: "~/metallb.configmap.yml"
      mode: 0664
    when: ansible_host == hostvars[groups['controller'][0]]['ansible_host'] | default(groups['controller'][0])
  
  - name: Deploy metallb ConfigMap
    k8s:
      kubeconfig: "/home/{{ ansible_user }}/.kube/config" 
      state: present              
      src: "~/metallb.configmap.yml"
    when: 
      - ansible_host == hostvars[groups['controller'][0]]['ansible_host'] | default(groups['controller'][0])

  when: 
    - metallb_deploy == true