- name: Debian Based OS - Install Kubernetes Components
  block: 
  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version_split[0] }}.{{ k8s_version_split[1] }}/deb/Release.key"
      state: present
  
  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: "deb https://pkgs.k8s.io/core:/stable:/v{{ k8s_version_split[0] }}.{{ k8s_version_split[1] }}/deb/ /"
      state: present
      filename: kubernetes.list
  
  - name: Install Kubelet
    apt:
      name: kubelet={{k8s_version}}*
      state: present
      update_cache: true
    register: apt_result
    until: apt_result is success
    retries: 10
    delay: 15
  
  - name: Install Kubeadm
    apt:
      name: kubeadm={{k8s_version}}*
      state: present
      update_cache: true
    register: apt_result
    until: apt_result is success
    retries: 10
    delay: 15
  when: ansible_os_family == "Debian"

- name: RedHat Based OS - Install Kubernetes Components
  block:
  - name: Add Kubernetes repository
    ansible.builtin.yum_repository:
      name: kubernetes
      description: Kubernnetes
      baseurl: https://pkgs.k8s.io/core:/stable:/v{{ k8s_version_split[0] }}.{{ k8s_version_split[1] }}/rpm/
      enabled: true
      gpgcheck: true
      gpgkey: https://pkgs.k8s.io/core:/stable:/v{{ k8s_version_split[0] }}.{{ k8s_version_split[1] }}/rpm/repodata/repomd.xml.key
      exclude: kubelet kubeadm kubectl
  
  - name: Install Kubelet
    yum:
      name: "kubelet-{{k8s_version}}"
      state: present
      update_cache: true
      disable_excludes: kubernetes
    register: yum_result
    until: yum_result is success
    retries: 10
    delay: 15
  
  - name: Install Kubeadm
    yum:
      name: "kubeadm-{{k8s_version}}"
      state: present
      update_cache: true
      disable_excludes: kubernetes
    register: yum_result
    until: yum_result is success
    retries: 10
    delay: 15
  when: ansible_os_family == "RedHat"

- name: Start Kubelet
  service:
    name: kubelet
    enabled: true
    state: started

# Join worker nodes 
- name: Join Worker Nodes
  block: 
  - name: Check if kubeadm directory exists.
    stat:
      path: /etc/kubernetes/kubeadm
    register: kdm_folder
  
  - name: "Create kubeadm directory if not exists"
    file:
      path: /etc/kubernetes/kubeadm/
      state: directory
      mode: 0755
    when: kdm_folder.stat.exists == false
  
  - name: Set up the kubeadm config file.
    template:
      src: "templates/{{ item.template }}"
      dest: "{{ item.dest }}"
      mode: 0644
    with_items:
      - { template: kubeadm-join.j2, dest: /etc/kubernetes/kubeadm/kubeadm-config.yml }
  
  - name: join cluster as worker
    shell: "sudo kubeadm join --config=/etc/kubernetes/kubeadm/kubeadm-config.yml"
  when: ansible_facts.fqdn not in hostvars[groups['controller'][0]].worker_nodes | json_query('resources[*].metadata.name')
