---
k8s_version: 1.32.11

docker_version: 27.5.1

containerdio_version: 1.7.28

containerd_version: 1.7.28

# this is the user that has ssh access to these machines
ansible_user: ansibleuser
systemd_dir: /etc/systemd/system

# Set your timezone
system_timezone: "Your/Timezone"

# Set CNI plugin choice flannel, calico or canal
cni_plugin: "calico"

# interface which will be used for cni binding
cni_iface: "eth0"

# POD Subnet
# check cni documentation for the appropriate cidr
podsubnet: "10.244.0.0/16"

# apiserver_endpoint is virtual ip-address of the load balancer
apiserver_endpoint: "192.168.1.17"

# Default Gateway
default_gateway: "192.168.1.1"

# Nameservers to use in resolv.conf.
dns_nameservers:
  - "9.9.9.9"
  - "1.1.1.1"

# NFS Client Configuration 
nfs_server: "192.168.1.10"
nfs_path: "/srv/nfs/kubedata"

# Mapping of hardware MAC addresses should be configured with specific IPs and Hostnames
ip_address_mapping:
  "192.168.1.11":
    name: ctrl-01.example.local
  "192.168.1.12":
    name: ctrl-02.example.local
  "192.168.1.15":
    name: ctrl-03.example.local
  "192.168.1.16":
    name: ctrl-04.example.local
  "192.168.1.13":
    name: wrkr-01.example.local
  "192.168.1.17":
    name: wrkr-02.example.local
  "192.168.1.14":
    name: ldbl-01.example.local
  "192.168.1.18":
    name: ldbl-02.example.local

# CNI Manifest URLs
# Calico Manifest url 
calico_url: "https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/tigera-operator.yaml"
calico_crd: "https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/custom-resources.yaml"
# Flannel Manifest URL
flannel_url: "https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml"
# Canal Manifest URL 
canal_url: "https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/canal.yaml"