# Install Container Runtime
- name: Add an apt signing key for Docker
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: Install docker-ce
  apt:
    name: docker-ce=5:{{ docker_version }}~3-0~{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}
    state: present
    update_cache: true
 #   install_recommends: no
    allow_downgrade: yes
  register: apt_result
  until: apt_result is success
  retries: 10
  delay: 5

- name: Install docker-ce-cli
  apt:
    name: docker-ce-cli=5:{{ docker_version }}~3-0~{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}
    state: present
    update_cache: true
    install_recommends: no
    allow_downgrade: yes

- name: Install containerd.io
  apt:
    name: containerd.io={{ containerd_version }}-1
    state: present
    update_cache: true
    allow_downgrade: yes

- name: Delete containerd config.toml
  file:
    state: absent
    path: /etc/containerd/config.toml
  notify:
    - Restart Docker
    - Restart Containerd

